Editing task 15315
MicrosoftDocs/power-pages-docs pull request #104
Opened 2023-12-05 15:36 UTC by MikaGriggs

2023-12-06 16:33 UTC, rhanajoy requested changes

2023-12-06 16:33 UTC, rhanajoy commented on power-pages-docs/admin/admin-center-analytics.md
> +Within the selected environment, you can also select a specific site for which you want to see the traffic. Select the Site ID from the list (Multiple sites can be selected by using **Ctrl + Click**)
~Within the selected environment, you can also select a specific site for which you want to see the traffic. Select the Site ID from the list (Multiple sites can be selected by using **Ctrl + Click**) to see traffic for that site.~
To view the traffic for a specific site, select it in the **Site ID** list. To view the traffic for multiple sites, select **Ctrl** while you select the sites in the list.

I looked this one up for confirmation, too. :) https://learn.microsoft.com/en-us/style-guide/procedures-instructions/describing-alternative-input-methods
![image](https://github.com/MicrosoftDocs/power-pages-docs/assets/12194458/ef708c5d-0355-4e26-aa8f-44e8f78925c0)

2023-12-06 16:33 UTC, rhanajoy commented on power-pages-docs/admin/admin-center-analytics.md
>  :::image type="content" source="Media/admin-center-analytics/analytics-site-id.png" alt-text="A screenshot fo the Power Platform admin center showing the Analytics Usage Data's Site ID dropdown.":::
~A screenshot fo the Power~
Screenshot of the Power

Just to be sure (that "left pane" thing shook me!), I looked up our guidance for structuring alt text. [Accessibility guidelines for images and videos](https://review.learn.microsoft.com/en-us/help/contribute/contribute-accessibility-multimedia?branch=main#alt-text-requirements-for-images) does in fact say to start alt text for screenshots with "Screenshot." Whew, I was right! :D BUT, the rest of the alt text should be tweaked to match the guidance in this section: https://review.learn.microsoft.com/en-us/help/contribute/contribute-accessibility-multimedia?branch=main#screenshots-of-user-interface

2023-12-14 16:05 UTC, closed without merging

2023-12-14 16:06 UTC, MikaGriggs commented
Made changes in the public repo--moved changes to the private repo and closed this request